### ISSUE TITLE
LAB_06, the default items in Azure portal don't match the lab

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/Secure-Azure-with-Microsoft-Defender-Cloud-Compliance-Controls#15]
#### Step: 2

Replace:
Availability options | Leave the default of No infrastructure redundancy required.
-- | --
Security type | Leave the default of Standard.

With:
Availability options | From the Availability Zone drop-down menu, select No infrastructure redundancy required
-- | --
Security type | From the Security type drop-down menu, select Standard

**Comment by serling1962** [comment]
Updates applied. Thank you.
