### ISSUE TITLE
Incomplete instructions to enable JIT for VMs

### ISSUE THREAD

**Issue by MSFT-mengchong** [MicrosoftLearning/Secure-Azure-with-Microsoft-Defender-Cloud-Compliance-Controls#19]
# Module: 00
#### Step: 03

Description of issue
The instructions are incomplete as the UI has changed.  It should say "In the menu, select Settings > Configuration."

![image](https://github.com/user-attachments/assets/7c7a9089-b5a3-46fd-ada5-0ece9e86adf2)

**Comment by serling1962** [comment]
The lab instructions are aligned with Skillable hosted environment.

**Comment by serling1962** [comment]
The lab instructions are aligned with Skillable hosted environment.
