### ISSUE TITLE
Need to add public IP address of client/customer device for administration purposes

### ISSUE THREAD

**Issue by MSFT-mengchong** [MicrosoftLearning/Secure-Azure-with-Microsoft-Defender-Cloud-Compliance-Controls#20]
# Module: 00
#### Step: 06

Description of issue
The public IP address of the client/customer device needs to be added for administration purposes.

![image](https://github.com/user-attachments/assets/994bafe0-232e-4958-b530-9f0cd8b0e465)

If not, the following error will appear in Lab 06B when attempting to manage the Azure KeyVault secrets.
"Firewall is turned on and your client IP address is not authorized to access this key vault."

![image](https://github.com/user-attachments/assets/680b875f-722c-46dc-974b-6a357d531c7e)

**Comment by serling1962** [comment]
The lab instructions are aligned with Skillable hosted environment.
