### ISSUE TITLE
No instructions to include necessary Azure RBAC roles to manage keys, secrets or certificates.

### ISSUE THREAD

**Issue by MSFT-mengchong** [MicrosoftLearning/Secure-Azure-with-Microsoft-Defender-Cloud-Compliance-Controls#21]
# Module: 00
#### Step: 04

Description of issue
Insufficient Azure RBAC permission to view secrets

There are no instructions to include the necessary Azure RBAC permissions to manage Azure KeyVault keys, secrets or certificates.  By default, the inherited Azure RBAC Owner role has insufficient permissions to perform those tasks.

![image](https://github.com/user-attachments/assets/cb01d9dd-0596-4566-a554-51b5346f983c)

There isn't sufficient Azure RBAC/IAM permission to manage Azure KeyVault secrets.  If using Azure Built-in RBAC roles, minimally requires Azure KeyVault Administrator RBAC role.

Keys
![image](https://github.com/user-attachments/assets/cc9afc69-2342-4895-ac11-abdcba2172e2)

Secrets
![image](https://github.com/user-attachments/assets/21134f90-022b-4dbc-bc04-42e2abebc4e0)

Certificates
![image](https://github.com/user-attachments/assets/37a8d7b2-0385-400f-9980-010954acce28)

https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/security#key-vault-administrator

**Comment by serling1962** [comment]
The lab instructions are aligned with Skillable hosted environment.
